"""
Django settings for property project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""





from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

TESTING = bool(os.environ.get("PYTEST_CURRENT_TEST"))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env
load_dotenv(BASE_DIR / ".env")

# Cache TTL for geocode results (seconds)
GEO_CACHE_TTL_SECONDS = 60 * 60 * 24 * 7  # 7 days


OTP_EXPIRY_MINUTES = 10


# -----------------------------
# Core security / environment
# -----------------------------
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    # Safe behaviour:
    # - local/dev/testing: allow a temporary key so you can still run
    # - production: you MUST set DJANGO_SECRET_KEY
    if os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"} or TESTING:
        SECRET_KEY = "dev-only-unsafe-secret-key-change-me"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY is required in production.")

DEBUG = os.getenv("DJANGO_DEBUG", "true").lower() in {"1", "true", "yes"}

# -----------------------------
# Production-grade security (staging + production)
# -----------------------------
if not DEBUG:
    # Render terminates TLS and forwards requests to Django.
    # This tells Django the original scheme was https.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Force HTTPS
    SECURE_SSL_REDIRECT = True

    # Secure cookies over HTTPS only
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Sensible baseline headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = "DENY"

    # HSTS (start low; increase later once confirmed stable)
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "3600"))  # 1 hour
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True




def _csv_env(name: str, default: str = ""):
    raw = os.getenv(name, default)
    return [x.strip() for x in raw.split(",") if x.strip()]

# ALLOWED_HOSTS:
# - production/staging (DEBUG=False): must be explicit and strict (no wildcard)
# - local/dev (DEBUG=True): allow local + convenience wildcard for Render previews if needed
ALLOWED_HOSTS = _csv_env(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost" if DEBUG else "",
)

if not DEBUG and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must be set in production")

if DEBUG:
    # Convenience for dev only (never in production)
    if ".onrender.com" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(".onrender.com")




# -----------------------------
# Stripe / site URLs
# -----------------------------
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.getenv("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")
SITE_URL = os.getenv("SITE_URL", "").strip()

# Frontend base URL used for links in emails
FRONTEND_BASE_URL = os.getenv("FRONTEND_BASE_URL", "https://rentout.co.uk")
IDEAL_POSTCODES_API_KEY = os.getenv("IDEAL_POSTCODES_API_KEY", "").strip()
GOOGLE_WEB_CLIENT_ID = os.getenv("GOOGLE_WEB_CLIENT_ID", "").strip()
APPLE_AUDIENCE = os.getenv("APPLE_AUDIENCE", "").strip()
# -----------------------------
# Application definition
# -----------------------------
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "propertylist_app.apps.PropertylistAppConfig",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "django_filters",
    "corsheaders",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "notifications.apps.NotificationsConfig",
    "django_celery_beat",
    "user_app",
   
   


]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "property.middleware.RequestIDMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "property.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "property.wsgi.application"

# -----------------------------
# Database (PostgreSQL via env vars)
# -----------------------------
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST", "127.0.0.1"),
        "PORT": os.getenv("DB_PORT", "5432"),
    }
}

# Hard stop in production if missing DB env vars
if not TESTING and not DEBUG:
    missing = [k for k in ["DB_NAME", "DB_USER", "DB_PASSWORD"] if not os.getenv(k)]
    if missing:
        raise ImproperlyConfigured(f"Missing required DB env vars: {', '.join(missing)}")

# -----------------------------
# Password validation
# -----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# -----------------------------
# Internationalization
# -----------------------------
LANGUAGE_CODE = "en-gb"
TIME_ZONE = "Europe/London"
USE_I18N = True
USE_TZ = True

# -----------------------------
# Static + Media
# -----------------------------
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use WhiteNoise in production (Render) so collectstatic works properly
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

#-----Media--------#
MEDIA_URL = "/media/"

# Use Render Disk when available so uploads persist across deploys
RENDER_DISK_PATH = os.environ.get("RENDER_DISK_PATH", "/var/data")
MEDIA_ROOT = Path(os.environ.get("MEDIA_ROOT", os.path.join(RENDER_DISK_PATH, "media")))



DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------
# DRF / OpenAPI / JWT
# -----------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
        "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    
    "DEFAULT_THROTTLE_RATES": {
        
        "user": "120/hour",
        "anon": "30/hour",

        "login": "5/minute",
        "register": "5/hour",
        "register_anon": "3/hour",

        "message_user": "12/hour",
        "messaging": "24/hour",

        "review-create": "5/hour",

        "password-reset": "3/hour",
        "password-reset-confirm": "5/hour",

        "report-create": "3/hour",
        "moderation": "30/hour",

        "otp-verify": "5/minute",
        "otp-resend": "2/hour",
    },
    
        
        
        
    
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
    ],
    "DEFAULT_PAGINATION_CLASS": "propertylist_app.api.pagination.StandardLimitOffsetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": (
        "propertylist_app.api.renderers.EnvelopeJSONRenderer",
    ),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "ALLOWED_VERSIONS": ["v1"],
    "VERSION_PARAM": "version",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "propertylist_app.api.exceptions.custom_exception_handler",
    "DEFAULT_VERSION": "v1",
}


OTP_EXPIRY_MINUTES = 10
OTP_MAX_ATTEMPTS = 5
OTP_RESEND_COOLDOWN_SECONDS = 60



# Reason: avoid hardcoding and ensure Swagger "Servers" matches the current environment domain.
# property/settings.py

# property/settings.py

SPECTACULAR_SETTINGS = {
    "TITLE": "RentOut API",
    "VERSION": "v1",
    "DESCRIPTION": "Backend API for RentOut property platform.",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": r"/api/v1",
    "SERVERS": [
        *(
            [{
                "url": SITE_URL.rstrip("/"),
                "description": "Current environment",
            }]
            if SITE_URL
            else []
        ),
        {
            "url": "https://rentout-staging-v2.onrender.com",
            "description": "Staging",
        },
    ],
    
    "ENUM_NAME_OVERRIDES": {
        "RoomStatusEnum": "propertylist_app.api.schema_enums.ROOM_STATUS_CHOICES",
        "BookingStatusEnum": "propertylist_app.api.schema_enums.BOOKING_STATUS_CHOICES",
        "ReviewRoleEnum": "propertylist_app.api.schema_enums.REVIEW_ROLE_CHOICES",
        "UserRoleEnum": "propertylist_app.api.schema_enums.USER_ROLE_CHOICES",
        "SmokingEnum": "propertylist_app.api.schema_enums.SMOKING_CHOICES",
        "YesNoNoPreferenceEnum": "propertylist_app.api.schema_enums.YES_NO_NO_PREFERENCE_CHOICES",
        "StripeIntentStatusEnum": "propertylist_app.api.schema_enums.STRIPE_INTENT_STATUS_CHOICES",
    },
    "POSTPROCESSING_HOOKS": [
        "propertylist_app.api.schema_hooks.wrap_success_responses",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# -----------------------------
# Security / Abuse controls
# -----------------------------
ENABLE_CAPTCHA = os.getenv("ENABLE_CAPTCHA", "true" if not DEBUG else "false").lower() in {"1", "true", "yes"}
CAPTCHA_PROVIDER = os.getenv("CAPTCHA_PROVIDER", "recaptcha")
CAPTCHA_SECRET = os.getenv("CAPTCHA_SECRET", "")

if ENABLE_CAPTCHA and not CAPTCHA_SECRET:
    raise ImproperlyConfigured("CAPTCHA_SECRET must be set when CAPTCHA is enabled")


ACCOUNT_DELETION_GRACE_DAYS = 7


LOGIN_FAIL_LIMIT = int(os.getenv("LOGIN_FAIL_LIMIT", "5"))
LOGIN_LOCKOUT_SECONDS = int(os.getenv("LOGIN_LOCKOUT_SECONDS", "900"))

# -----------------------------
# CORS / CSRF
# (keep local defaults; override via env later if you want)
# -----------------------------
CORS_ALLOWED_ORIGINS = _csv_env(
    "CORS_ALLOWED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000" if DEBUG else "",
)

if not DEBUG and not CORS_ALLOWED_ORIGINS:
    raise ImproperlyConfigured("CORS_ALLOWED_ORIGINS must be set in production")

CSRF_TRUSTED_ORIGINS = _csv_env(
    "CSRF_TRUSTED_ORIGINS",
    "http://localhost:3000,http://127.0.0.1:3000" if DEBUG else "",
)

if not DEBUG and not CSRF_TRUSTED_ORIGINS:
    raise ImproperlyConfigured("CSRF_TRUSTED_ORIGINS must be set in production")
# -----------------------------
# Email
# -----------------------------
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    "django.core.mail.backends.smtp.EmailBackend" if not DEBUG else "django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@rentout.local")
SERVER_EMAIL = os.getenv("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

if not DEBUG:
    missing_email = [
        k for k in ["EMAIL_HOST", "EMAIL_HOST_USER", "EMAIL_HOST_PASSWORD"]
        if not os.getenv(k)
    ]
    if missing_email:
        raise ImproperlyConfigured(
            f"Missing required email env vars in production: {', '.join(missing_email)}"
        )

# -----------------------------
# Media policy knobs used by validators
# -----------------------------
MAX_IMAGE_BYTES = int(os.getenv("MAX_IMAGE_BYTES", str(5 * 1024 * 1024)))  # 5 MB
ALLOWED_IMAGE_FORMATS = {"JPEG", "JPG", "PNG", "WEBP"}
MAX_IMAGE_PIXELS = int(os.getenv("MAX_IMAGE_PIXELS", "40000000"))  # 40 MP safety fuse

# -----------------------------
# Optional S3 storage (toggle via env)
# -----------------------------
USE_S3 = os.getenv("USE_S3", "false").lower() in {"1", "true", "yes"}

if USE_S3:
    INSTALLED_APPS += ["storages"]  # requires django-storages
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"

    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME", "")
    if not AWS_STORAGE_BUCKET_NAME:
        raise ImproperlyConfigured("AWS_STORAGE_BUCKET_NAME must be set when USE_S3=True")
    AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "eu-west-2")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_S3_ADDRESSING_STYLE = "virtual"
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None

    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = int(os.getenv("AWS_QUERYSTRING_EXPIRE", "900"))

    AWS_S3_OBJECT_PARAMETERS = {
        "ServerSideEncryption": "AES256",
        "CacheControl": "max-age=86400, s-maxage=86400",
    }

    AWS_S3_CUSTOM_DOMAIN = os.getenv("AWS_S3_CUSTOM_DOMAIN", "")

# -----------------------------
# Webhook secrets (read from environment)
# -----------------------------
WEBHOOK_SECRETS = {
    "default": os.environ.get("WEBHOOK_SECRET", ""),
    "stripe": os.environ.get("STRIPE_WEBHOOK_SECRET", ""),
}





# -----------------------------
# Caching
# -----------------------------
REDIS_URL = os.getenv("REDIS_CACHE_URL")

if not REDIS_URL and not DEBUG:
    raise ImproperlyConfigured("REDIS_CACHE_URL must be set in production")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": REDIS_URL or "redis://127.0.0.1:6379/2",
        "KEY_PREFIX": "rentcrib",
    }
}

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", "redis://127.0.0.1:6379/1")

CACHE_DEFAULT_TTL = 60
CACHE_SEARCH_TTL = 120

# -----------------------------
# GDPR policy knobs
# -----------------------------
GDPR_RETENTION = {
    "export_link_days": 7,
}
GDPR_HASH_SALT = os.getenv("GDPR_HASH_SALT", "dev-insecure-salt")

if not DEBUG and GDPR_HASH_SALT == "dev-insecure-salt":
    raise ImproperlyConfigured("GDPR_HASH_SALT must be set in production")

# -----------------------------
# Celery (single canonical configuration)
# NOTE: Beat schedule must live in celery_app.py (NOT here)
# -----------------------------

CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# Celery routing safety: even if django-celery-beat PeriodicTask queue/routing_key are NULL,
# Celery will still publish tasks to the queue our worker consumes.
CELERY_TASK_DEFAULT_QUEUE = "celery"
CELERY_TASK_DEFAULT_ROUTING_KEY = "celery"
CELERY_TASK_DEFAULT_EXCHANGE = "celery"
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = "direct"



CELERY_TASK_ALWAYS_EAGER = False
CELERY_TASK_TIME_LIMIT = 60
CELERY_TASK_SOFT_TIME_LIMIT = 45

CELERY_TASK_ROUTES = {
    "notifications.tasks.*": {"queue": "emails"},
    "propertylist_app.tasks.task_send_new_message_email": {"queue": "emails"},
    "propertylist_app.expire_paid_listings": {"queue": "maintenance"},
}



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "request_id": {"()": "property.logging.RequestIDLogFilter"},
    },
    "formatters": {
        "standard": {
            "format": "%(levelname)s %(asctime)s request_id=%(request_id)s %(name)s %(message)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "filters": ["request_id"],
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    # Keep django.request visible (500s etc)
    "loggers": {
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": True,
        },
    },
}

