# Generated by Django 5.2.4 on 2025-07-20 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('about', models.TextField(max_length=150)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=8)),
                ('location', models.CharField(max_length=255)),
                ('available_from', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('ensuite', 'En-suite Room'), ('studio', 'Studio Room'), ('shared', 'Shared Room'), ('box', 'Box Room'), ('master', 'Master Bedroom'), ('loft', 'Loft Room'), ('bedsit', 'Bedsit')], max_length=100)),
                ('furnished', models.BooleanField(default=False)),
                ('bills_included', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='room_images/')),
                ('number_of_bedrooms', models.IntegerField()),
                ('number_of_bathrooms', models.IntegerField()),
                ('property_type', models.CharField(choices=[('flat', 'Flat'), ('house', 'House'), ('studio', 'Studio')], max_length=100)),
                ('parking_available', models.BooleanField(default=False)),
                ('property_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RoomList',
        ),
    ]
