# Generated by Django 5.2.4 on 2025-07-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0002_roomcategory_room_delete_roomlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomCategory',
            new_name='RoomCategorie',
        ),
    ]
