# Generated by Django 5.2.4 on 2025-07-21 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0004_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='propertylist_app.roomcategorie'),
            preserve_default=False,
        ),
    ]
