# Generated by Django 5.2.4 on 2025-08-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0006_remove_room_room_type_alter_room_category_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
