# Generated by Django 5.2.4 on 2025-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0011_room_deleted_at_room_is_deleted_roomimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
