# Generated by Django 5.2.4 on 2025-09-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0015_message_propertylis_thread__9a4846_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
