# Generated by Django 5.2.4 on 2025-09-24 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0016_booking_canceled_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilitySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(db_index=True)),
                ('end', models.DateTimeField(db_index=True)),
                ('max_bookings', models.PositiveIntegerField(default=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='propertylist_app.room')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='propertylist_app.availabilityslot'),
        ),
        migrations.AddIndex(
            model_name='availabilityslot',
            index=models.Index(fields=['room', 'start'], name='propertylis_room_id_5888e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('room', 'start', 'end'), name='uq_room_slot'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='ck_slot_end_gt_start'),
        ),
    ]
