# Generated by Django 5.2.4 on 2025-09-24 23:37

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0017_availabilityslot_booking_slot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='uq_room_title_lower',
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), condition=models.Q(('is_deleted', False)), name='uq_room_title_lower_alive'),
        ),
    ]
