# Generated by Django 5.2.4 on 2025-09-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0018_remove_room_uq_room_title_lower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategorie',
            name='about',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='website',
            field=models.URLField(max_length=255),
        ),
    ]
