# Generated by Django 5.2.4 on 2025-09-27 01:39

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0019_alter_roomcategorie_about_alter_roomcategorie_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ('start',)},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveConstraint(
            model_name='availabilityslot',
            name='uq_room_slot',
        ),
        migrations.RemoveConstraint(
            model_name='availabilityslot',
            name='ck_slot_end_gt_start',
        ),
        migrations.RemoveIndex(
            model_name='availabilityslot',
            name='propertylis_room_id_5888e1_idx',
        ),
        migrations.AddField(
            model_name='availabilityslot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomcategorie',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='roomcategorie',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='availabilityslot',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='about',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='website',
            field=models.URLField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['room', 'review_user'], name='propertylis_room_id_0d984a_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['room', 'created'], name='propertylis_room_id_2dcae6_idx'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='slot_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.CheckConstraint(condition=models.Q(('max_bookings__gte', 1)), name='slot_max_bookings_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='availabilityslot',
            constraint=models.UniqueConstraint(fields=('room', 'start', 'end'), name='unique_slot_room_start_end'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('room', 'review_user'), name='uq_review_once_per_room'),
        ),
    ]
