# Generated by Django 5.2.4 on 2025-09-28 04:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0020_alter_availabilityslot_options_alter_review_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe')], default='stripe', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=200)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires payment'), ('requires_action', 'Requires action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='requires_payment_method', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='propertylist_app.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='propertylis_user_id_ee5e2b_idx'), models.Index(fields=['room', 'created_at'], name='propertylis_room_id_4ca661_idx'), models.Index(fields=['stripe_payment_intent_id'], name='propertylis_stripe__e33531_idx'), models.Index(fields=['stripe_checkout_session_id'], name='propertylis_stripe__87a356_idx')],
            },
        ),
    ]
