# Generated by Django 5.2.4 on 2025-09-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0023_room_status_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookreceipt',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookreceipt',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
