# Generated by Django 5.2.4 on 2025-10-15 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0025_gdprtombstone_dataexport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={},
        ),
    ]
