# Generated by Django 5.2.4 on 2025-10-16 00:33

import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0026_alter_availabilityslot_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilityslot',
            options={'ordering': ('start',)},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='propertylis_thread__9a4846_idx',
        ),
        migrations.RemoveField(
            model_name='message',
            name='created_at',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='available_from',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='number_of_bedrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='about',
            field=models.TextField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='key',
            field=models.CharField(blank=True, default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='roomcategorie',
            name='website',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['thread', 'created'], name='propertylis_thread__36a5fb_idx'),
        ),
    ]
