# Generated by Django 5.2.4 on 2025-10-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0030_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='room',
            name='uq_room_title_lower_alive',
        ),
        migrations.AddField(
            model_name='message',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
