# Generated by Django 5.2.4 on 2025-10-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propertylist_app", "0031_remove_room_uq_room_title_lower_alive_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="message",
                    name="updated",
                    field=models.DateTimeField(auto_now=True, db_index=True),
                ),
                migrations.AddIndex(
                    model_name="message",
                    index=models.Index(
                        fields=["thread", "updated"],
                        name="propertylis_thread__9ea7d2_idx",
                    ),
                ),
            ],
        ),
    ]
