# Generated by Django 5.2.4 on 2025-10-28 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0032_add_message_updated'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='propertylis_thread__9ea7d2_idx',
            old_name='message_thread_updated_idx',
        ),
    ]
