# Generated by Django 5.2.4 on 2025-11-13 02:11

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0034_userprofile_email_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailotp',
            name='code_hash',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='code',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), condition=models.Q(('is_deleted', False)), name='uq_room_title_lower_alive'),
        ),
    ]
