# Generated by Django 5.2.4 on 2025-11-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0035_remove_emailotp_code_hash_emailotp_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_shared_room',
            field=models.BooleanField(default=False, help_text='Room is in an existing flat/house share.'),
        ),
        migrations.AddField(
            model_name='room',
            name='max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='max_stay_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='min_stay_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_for',
            field=models.CharField(choices=[('any', "Don't mind"), ('females', 'Females'), ('males', 'Males'), ('couples', 'Couples')], default='any', max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='room_size',
            field=models.CharField(choices=[('dont_mind', "Don't mind"), ('single', 'Single'), ('double', 'Double')], default='dont_mind', max_length=16),
        ),
    ]
