# Generated by Django 5.2.4 on 2025-11-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0037_messagethreadstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethreadstate',
            name='label',
            field=models.CharField(choices=[('none', 'No Status'), ('viewing_scheduled', 'Viewing Scheduled'), ('viewing_done', 'Viewing Done'), ('good_fit', 'Good Fit'), ('unsure', 'Unsure'), ('not_a_fit', 'Not a Fit'), ('paperwork_pending', 'Paperwork Pending')], db_index=True, default='none', max_length=32),
        ),
    ]
