# Generated by Django 5.2.4 on 2025-12-05 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0038_messagethreadstate_label'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagethreadstate',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='messagethreadstate',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='messagethread',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='messagethread',
            name='label',
            field=models.CharField(
                blank=True,
                db_index=True,
                default='',
                help_text="Optional label for this thread (e.g. 'Viewing scheduled', 'Good fit').",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='messagethreadstate',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now,   # <-- FIXED HERE
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagethreadstate',
            name='in_bin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagethreadstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='about_you',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                blank=True,
                choices=[
                    ('male', 'Male'),
                    ('female', 'Female'),
                    ('non_binary', 'Non-binary'),
                    ('prefer_not_to_say', 'Prefer not to say'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='messagethreadstate',
            name='label',
            field=models.CharField(
                blank=True,
                choices=[
                    ('viewing_scheduled', 'Viewing scheduled'),
                    ('viewing_done', 'Viewing done'),
                    ('good_fit', 'Good fit'),
                    ('unsure', 'Unsure'),
                    ('not_a_fit', 'Not a fit'),
                    ('paperwork_pending', 'Paperwork pending'),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name='messagethreadstate',
            name='thread',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='states',
                to='propertylist_app.messagethread',
            ),
        ),
        migrations.AddIndex(
            model_name='messagethreadstate',
            index=models.Index(
                fields=['user', 'thread'],
                name='propertylis_user_id_7c13bb_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='messagethreadstate',
            index=models.Index(
                fields=['user', 'in_bin'],
                name='propertylis_user_id_d16974_idx',
            ),
        ),
        migrations.AddIndex(
            model_name='messagethreadstate',
            index=models.Index(
                fields=['user', 'label'],
                name='propertylis_user_id_ff84b6_idx',
            ),
        ),
    ]
