# Generated by Django 5.2.4 on 2025-12-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0039_remove_messagethreadstate_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address_manual',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role_detail',
            field=models.CharField(blank=True, choices=[('live_in_landlord', 'Live in Landlord'), ('live_out_landlord', 'Live Out Landlord'), ('current_flatmate', 'Current Flatmate'), ('former_flatmate', 'Former Flatmate'), ('agent_broker', 'Real Estate Agent/Broker')], default='', max_length=32),
        ),
    ]
