# Generated by Django 5.2.4 on 2025-12-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0042_contactmessage_alter_userprofile_role_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='view_available_custom_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of specific viewing dates when mode is 'custom'."),
        ),
        migrations.AddField(
            model_name='room',
            name='view_available_days_mode',
            field=models.CharField(choices=[('everyday', 'Everyday'), ('weekdays', 'Weekdays only'), ('weekends', 'Weekends only'), ('custom', 'Custom dates')], default='everyday', help_text='Everyday / weekdays only / weekends only / custom dates.', max_length=20),
        ),
    ]
