# Generated by Django 5.2.4 on 2025-12-08 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0043_room_view_available_custom_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='availability_from_time',
            field=models.TimeField(blank=True, help_text='Earliest time you are available (e.g. 16:30).', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='availability_to_time',
            field=models.TimeField(blank=True, help_text='Latest time you are available (e.g. 20:00).', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='available_from',
            field=models.DateField(default=datetime.date.today, help_text='Date from which the room will be available for listing / move-in.'),
        ),
    ]
