# Generated by Django 5.2.4 on 2025-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0044_room_availability_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='security_deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit in GBP.', max_digits=8, null=True),
        ),
    ]
