# Generated by Django 5.2.4 on 2025-12-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0045_room_security_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_shared_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('hidden', 'Hidden')], default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_available_custom_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_available_days_mode',
            field=models.CharField(choices=[('everyday', 'Everyday'), ('weekdays', 'Weekdays only'), ('weekends', 'Weekends only'), ('custom', 'Custom dates')], default='everyday', max_length=20),
        ),
    ]
