# Generated by Django 5.2.4 on 2025-12-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0046_alter_room_availability_from_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of selected amenity keys for this room.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_from_time',
            field=models.TimeField(blank=True, help_text='Earliest time you are available (e.g. 16:30).', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_to_time',
            field=models.TimeField(blank=True, help_text='Latest time you are available (e.g. 20:00).', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='is_shared_room',
            field=models.BooleanField(default=False, help_text='Room is in an existing flat/house share.'),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_available_custom_dates',
            field=models.JSONField(blank=True, default=list, help_text="List of specific viewing dates when mode is 'custom'."),
        ),
        migrations.AlterField(
            model_name='room',
            name='view_available_days_mode',
            field=models.CharField(choices=[('everyday', 'Everyday'), ('weekdays', 'Weekdays only'), ('weekends', 'Weekends only'), ('custom', 'Custom dates')], default='everyday', help_text='Everyday / weekdays only / weekends only / custom dates.', max_length=20),
        ),
    ]
