# Generated by Django 5.2.4 on 2025-12-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0047_room_amenities_alter_room_availability_from_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Approximate age of current flatmate or average age in the household.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_language',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_lgbtqia_household',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='', help_text='Whether the household includes LGBTQIA+ people.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_nationality',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_occupation',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('student', 'Student'), ('prefer_not_to_say', 'Prefer not to say')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_pets',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='', help_text='Are there pets in the home?', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='existing_flatmate_smoking',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='', help_text='Do existing flatmates smoke?', max_length=20),
        ),
    ]
