# Generated by Django 5.2.4 on 2025-12-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0048_remove_room_amenities_room_existing_flatmate_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='existing_flatmate_smoking',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', help_text='Do existing flatmates smoke?', max_length=20),
        ),
    ]
