# Generated by Django 5.2.4 on 2025-12-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0049_alter_room_existing_flatmate_smoking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_gender',
            field=models.CharField(blank=True, choices=[('no_preference', 'No preference'), ('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='no_preference', help_text='Preferred gender of future flatmate.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_language',
            field=models.CharField(blank=True, default='', help_text='Preferred language of future flatmate (free text from dropdown).', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_lgbtqia',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', help_text='Preference about LGBTQIA+ flatmates.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_max_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum preferred age of flatmate.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_min_age',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum preferred age of flatmate.', null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_nationality',
            field=models.CharField(blank=True, default='', help_text='Preferred nationality of future flatmate (free text from dropdown).', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_occupation',
            field=models.CharField(blank=True, choices=[('students_only', 'For students only'), ('not_for_students', 'Not for students'), ('open_to_everyone', 'Open to everyone')], default='', help_text='Student / non-student preference for future flatmate.', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_partners_allowed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default='no', help_text='Whether partners are allowed to stay over.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_pets',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', help_text='Whether future flatmate can have / be around pets.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_smoking',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', help_text='Whether future flatmate can smoke or not.', max_length=20),
        ),
        migrations.AddField(
            model_name='room',
            name='preferred_flatmate_vegan_vegetarian',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', help_text='Preference about vegan/vegetarian flatmates.', max_length=20),
        ),
    ]
