# Generated by Django 5.2.4 on 2025-12-11 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0050_room_preferred_flatmate_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
