# Generated by Django 5.2.4 on 2025-12-15 22:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0052_booking_deleted_at_booking_is_deleted_booking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveConstraint(
            model_name='review',
            name='uq_review_once_per_room',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='propertylis_room_id_0d984a_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='propertylis_room_id_2dcae6_idx',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created',
            new_name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review_user',
        ),
        migrations.RemoveField(
            model_name='review',
            name='room',
        ),
        migrations.RemoveField(
            model_name='review',
            name='update',
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='propertylist_app.booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='overall_rating',
            field=models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='reveal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, choices=[('tenant_to_landlord', 'Tenant → Landlord'), ('landlord_to_tenant', 'Landlord → Tenant')], max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('booking', 'role'), name='uq_review_once_per_booking_role'),
        ),
    ]
