# Generated by Django 5.2.4 on 2025-12-15 23:27
from django.db import migrations


def wipe_reviews(apps, schema_editor):
    # If the review table doesn't exist (e.g. was dropped during refactor),
    # skip safely.
    table_names = schema_editor.connection.introspection.table_names()
    if "propertylist_app_review" not in table_names:
        return

    Review = apps.get_model("propertylist_app", "Review")
    Review.objects.all().delete()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("propertylist_app", "0053_alter_review_options_and_more"),
    ]

    operations = [
        migrations.RunPython(wipe_reviews, migrations.RunPython.noop),
    ]




