# Generated by Django 5.2.4 on 2025-12-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0055_userprofile_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_confirmations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_reminders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_rentout_updates',
            field=models.BooleanField(default=True),
        ),
    ]
