# Generated by Django 5.2.4 on 2025-12-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0056_userprofile_notify_confirmations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='read_receipts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
