# Generated by Django 5.2.4 on 2025-12-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0057_userprofile_read_receipts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='allow_search_indexing_override',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allow_search_indexing_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_from_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='availability_to_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='preferred_flatmate_max_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='preferred_flatmate_min_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
