# Generated by Django 5.2.4 on 2025-12-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0058_room_allow_search_indexing_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en-GB', 'English (UK)'), ('en-US', 'English (US)')], default='en-GB', max_length=10),
        ),
    ]
