# Generated by Django 5.2.4 on 2025-12-28 02:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0059_userprofile_preferred_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emailotp',
            name='propertylis_user_id_906960_idx',
        ),
        migrations.AddField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email verification'), ('password_reset', 'Password reset')], default='email_verify', max_length=32),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', 'created_at'], name='propertylis_user_id_6a8a56_idx'),
        ),
    ]
