# Generated by Django 5.2.4 on 2025-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0060_remove_emailotp_propertylis_user_id_906960_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pending_deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_deletion_scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
