# Generated by Django 5.2.4 on 2025-12-29 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0061_userprofile_pending_deletion_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='accessible_entry',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='bathroom_type',
            field=models.CharField(blank=True, choices=[('private', 'Private'), ('shared', 'Shared'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='free_to_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='household_bedrooms_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='household_bedrooms_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='household_environment',
            field=models.CharField(blank=True, choices=[('quiet', 'Quiet'), ('sociable', 'Sociable'), ('mixed', 'Mixed'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='household_type',
            field=models.CharField(blank=True, choices=[('professional', 'Professional'), ('student', 'Student'), ('mixed', 'Mixed'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='inclusive_household',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='max_occupants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='room',
            name='pets_allowed',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='shared_living_space',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='smoking_allowed_in_property',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='room',
            name='suitable_for',
            field=models.CharField(blank=True, choices=[('one_person', 'One person'), ('couple', 'Couple'), ('max_occupants', 'Maximum occupants'), ('no_preference', 'No preference')], default='no_preference', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='advertiser_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
