# Generated by Django 5.2.4 on 2026-01-02 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0064_tenancy_review_tenancy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenancyExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_duration_months', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='proposed', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tenancy',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='tenancy',
            name='uq_tenancy_room_tenant_once',
        ),
        migrations.AddField(
            model_name='tenancy',
            name='still_living_landlord_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenancy',
            name='still_living_tenant_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenancyextension',
            name='proposed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenancy_extensions_proposed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenancyextension',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='propertylist_app.tenancy'),
        ),
        migrations.AddIndex(
            model_name='tenancyextension',
            index=models.Index(fields=['tenancy', 'status'], name='propertylis_tenancy_e967e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tenancyextension',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('tenancy',), name='uq_open_extension_per_tenancy'),
        ),
    ]
