# Generated by Django 5.2.4 on 2026-01-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0065_tenancyextension_alter_tenancy_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_tenant_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_tenant_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
