# Generated by Django 5.2.4 on 2026-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0066_userprofile_avg_tenant_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_landlord_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_landlord_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
