# Generated by Django 5.2.4 on 2026-03-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0068_notification_target_id_notification_target_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_role',
            field=models.CharField(blank=True, choices=[('', 'No admin role'), ('super_admin', 'Super Admin'), ('ops_admin', 'Operations Admin'), ('moderator', 'Moderation Admin'), ('finance_admin', 'Finance Admin'), ('support_admin', 'Support Admin')], db_index=True, default='', max_length=30),
        ),
    ]
