# Generated by Django 5.2.4 on 2026-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0069_userprofile_admin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookreceipt',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookreceipt',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
