# Generated by Django 5.2.4 on 2026-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0070_webhookreceipt_processed_webhookreceipt_processed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
