# Generated by Django 5.2.4 on 2026-04-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0071_alter_emailotp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
