# Generated by Django 5.2.4 on 2026-04-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0072_alter_phoneotp_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='uq_review_once_per_booking_role',
        ),
        migrations.RemoveField(
            model_name='review',
            name='booking',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('requires_payment_method', 'Requires payment'), ('requires_action', 'Requires action'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('canceled', 'Canceled')], default='requires_payment_method', max_length=40),
        ),
        migrations.AlterField(
            model_name='review',
            name='tenancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='propertylist_app.tenancy'),
        ),
    ]
