# Generated by Django 5.2.4 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0073_remove_review_uq_review_once_per_booking_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
