# Generated by Django 5.2.4 on 2026-05-03 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0074_alter_booking_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethread',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='role',
            field=models.CharField(blank=True, choices=[('tenant_to_landlord', 'Tenant â†’ Landlord'), ('landlord_to_tenant', 'Landlord â†’ Tenant')], max_length=32, null=True),
        ),
    ]
