# Generated by Django 5.2.4 on 2026-09-06 01:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertylist_app', '0095_merge_duplicate_message_threads'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='messagethreadstate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='messagethreadstate',
            index=models.Index(fields=['user', 'deleted_at'], name='propertylis_user_id_cacc1c_idx'),
        ),
    ]
